console.log('test');

/*-------------------------------- Constants --------------------------------*/
const wordPool = [{
    theory: ['approach', 'argument', 'assumption', 'concept', 'idea', 'ideology',
    'method','philosophy','plan','position','premise','proposal','rationale', 'speculation', 
    'suspicion', 'system', 'thesis', 'understanding', 'basis', 'feeling', 'guess', 'hunch',
    'outlook', 'presumption', 'surmise','hypothesis', 'suggestion', 'generalization', 'inkling',
    'speaker', 'nature', 'Darwin', 'science', 'rumor', 'question','conspiracy', 'evolution', 'model', 'experiment', 'prediction'],
     outcome: ['conclusion', 'event', 'fallout', 'issue',
    'reaction','result', 'aftereffect', 'aftermath', 'end', 'payback', 'score', 'cause',
    'win','consequence','effect','justify','reason','finish', 'decision', 'situation', 'scenario',
    'experience', 'fate', 'future', 'reward', 'victorious', 'path', 'game', 'lose', 'verdict', 'model', 'experiment', 'prediction'],
    desk: ['counter', 'standing', 'secretary', 'work', 'workspace', 'davenport', 'school', 'writing', 'wooden', 'hold', 
    'office', 'chair', 'homework','table', 'room', 'workstation', 'receptionist', 'reception',
    'tech', 'gaming', 'station'], 
    meal: ['snack', 'breakfast', 'lunch', 'dinner', 'food', 'knife', 'fork', 'spoon',
    'menu', 'dish', 'feast', 'entree', 'steak', 'eat', 'picnic', 'restaurant','nutrient',
    'recipe', 'service', 'dishes', 'kitchen', 'event', 'delivery', 'sleep', 'takeout', 'free',
    'money', 'thanksgiving', 'health', 'buffett', 'course', 'dollar', 'money', 'ingest', 'consume', 'cafe'],
    arrival: ['departure', 'return', 'appearance', 'landing', 'visit', 'annoucement', 'trip',
    'homecoming', 'incoming', 'income', 'entrance', 'welcome', 'presence', 'impending', 'birth',
    'visitor', 'late', 'shipping', 'delivery', 'creation', 'travel', 'travelling', 'holiday', 'flight'],
    birthday: ['celebration', 'cake', 'gift', 'party', 'celebrate', 'special', 'happy', 'dinner',
    'candle', 'festivities', 'group', 'age', 'yearly', 'year', 'suit', 'month', 'milestone', 'annually',
    'present', 'card', 'balloons', 'balloon', 'trip', 'friends', 'friend', 'hat'],
    weakness: ['strength', 'feeble', 'frail', 'vulnerable', 'slow', 'strong', 'imperfect', 'lower',
    'flimsy', 'dilute', 'fear', 'resist', 'damage', 'ineffective', 'exhaustion', 'muscle', 'limit',
    'limits', 'limitation', 'detriment', 'decline'],
    currency: ['money', 'coin', 'dollar', 'cash', 'bank', 'debt', 'country', 'credit', 'asset', 
    'store', 'liquid', 'paper', 'resource', 'gold', 'silver', 'exchange', 'finance', 'crypto', 'devaluation',
    'digital', 'power', 'shop', 'buy', 'sell', 'foreign', 'fees', 'transaction', 'rates', 'platform', 
    'debit', 'interest', 'product', 'products', 'wallet', 'purse', 'amount', 'count'],
    volume: ['mass', 'quantity', 'amount','weight', 'length', 'bulk', 'measure', 'gallon', 'density',
    'production', 'book', 'size', 'paperback', 'area', 'mute', 'music', 'sound', 'raise', 'lower', 
     'level', 'distance', 'audio', 'speaker', 'dimensions', 'shares','business', 'finance'],
    income: ['wealth', 'profit', 'revenue', 'salary', 'hourly', 'hustle', 'money', 'tax', 'wage',
    'benefits', 'debt', 'cash', 'debit', 'save', 'savings', 'account', 'employmeny', 'job', 'work',
    'expenses', 'expense', 'asset', 'value', 'raise', 'purchase', 'buy', 'cycle', 'check','business', 'finance'], 
    science: ['method', 'biology', 'chemistry', 'physics', 'math', 'technology', 'observation', 'hypothesis',
    'analytics', 'experiment', 'nature', 'human', 'data', 'predict', 'progress', 'health', 
    'institute', 'school', 'evidence', 'life', 'degree', 'test', 'evolution', 'grade', 'museum', 'measure',
    'study', 'formula', 'fiction', 'concept', 'teacher', 'instructor', 'hormone', 'subject', 'anatomy'], 
    connection: ['bond','link', 'attachment', 'contact', 'junction', 'association', 'relate', 
    'relevance', 'concatenation', 'communication', 'hookup', 'friend', 'friendship', 'affiliation',
    'intimacy', 'together', 'history', 'correlation', 'internet', 'spark', 'ping', 'sync', 'conversation',
    'feeling', 'interaction', 'parallels', 'signal', 'service', 'port', 'network', 'close', 'performance', 
    'bad', 'good', 'bridge', 'involved', 'fasten', 'join'],
    description: ['definition', 'title', 'characterization', 'explanation', 'explain', 'name', 'details',
    'text', 'picture', 'statement', 'summary', 'attributes', 'comment', 'story', 'match', 'matching', 'matches',
    'adjective', 'idea', 'suspect', 'about', 'transcript', 'parapgraph', 'type', 'write', 'intro', 'page', 
    'review', 'visual', 'visualize', 'quote', 'language'],
    love: ['bond', 'intimacy', 'adore', 'romance', 'passion', 'emotion', 'heart', 'kiss', 'cupid',
    'valentines', 'obsession', 'together', 'bird', 'rose', 'feeling', 'dream', 'song', 'sex', 'god', 
    'interest', 'marry', 'hormone', 'gift', 'language', 'fear', 'people', 'partner', 'self', 'flirty', 'fall'],
    media: ['news', 'internet', 'radio', 'network', 'video', 'social', 'sound', 'entertainment', 'computer',
    'public', 'people', 'digital', 'online', 'clips', 'footage', 'culture', 'picture', 'music', 'politics',
    'audience', 'web', 'influencer', 'viewer', 'event'],
    consequence: ['result', 'effect', 'outcome', 'impact', 'choice', 'punishment', 'aftermath', 'cause', 'action', 
    'repercussion', 'byproduct', 'risk', 'issue', 'cost', 'discipline', 'event', 'penalty', 'problem', 'danger', 
    'backlash', 'stress', 'fear', 'damage', 'regret', 'suffer', 'fail', 'failure'],
    pizza: ['cheese', 'food', 'italy', 'pepperoni', 'tomato', 'bread', 'sauce', 'restaurant', 'oven', 'leftover', 
    'slice', 'pie', 'dinner', 'lunch', 'frozen', 'pineapple', 'italian', 'kitchen', 'freezer', 'microwave', 'ingest',
    'consume'],
    cigarette: ['cigar', 'tobacco', 'nicotine', 'smoke', 'smoking', 'lungs', 'cancer', 'vape', 'butt', 'smoker',
    'inhale', 'gum', 'pack', 'drug', 'puff', 'lighter', 'light', 'fire', 'marlboro', 'taxes', 'expensive', 'menthol',
    'hit', 'smell', 'flavor', 'blunt', 'leaf', 'addictive', 'addicting', 'addict', 'product', 'import', 'ban', 'bans',
    'cancerous', 'abuse'],
    blood: ['heart', 'oxygen', 'hemoglobin', 'gore', 'horror', 'stream', 'plasma', 'inflection', 'organ', 'organs', 
    'liver', 'vein', 'kidney', 'brain', 'cells', 'cell', 'knife', 'human', 'vessel', 'platelet', 'fluid', 'lung',
    'stomach', 'red', 'iron', 'fluids', 'clot', 'pulse', 'transfusion', 'menstruation', 'type', 'test', 'ancestry', 
    'ancestor', 'nutrients', 'nutrient', 'circulation', 'circulate', 'injury', 'injuries', 'labs','lab', 'vampire',
    'sacrifice', 'moon', 'orange', 'murder', 'stab','donate', 'doantion', 'donations', 'donor', 'wound', 'vital'],
    dirt: ['stain', 'stains', 'mud', 'filth', 'clay', 'soil', 'grime', 'scandal', 'earth', 'ground', 'dust', 'muck',
    'muddy', 'debris', 'grass', 'pants', 'shoes', 'clothes', 'crap', 'ditches', 'ditch', 'gossip', 'trash', 'contamination',
    'contaminate', 'garbage', 'rocks', 'rock', 'manure', 'plants', 'plant', 'trees', 'tree', 'barefoot', 'street', 'germs', 
    'bugs', 'insects', 'bug', 'insect', 'moisture', 'grow', 'face', 'unclean', 'sediment', 'road', 'forest', 'pot'],
    trainer: ['waist', 'physical', 'coach', 'manager', 'instructor', 'condition', 'horse', 'breeder', 'box', 'boxer', 'teacher',
    'gym', 'pokemon', 'sneaker', 'fitness', 'improvement', 'improve', 'pet', 'dog', 'cat', 'workout', 'partner', 'strength',
    'stamina', 'bodybuilder', 'expert', 'program', 'person', 'exercise', 'mentor', 'teammate', 'educate', 'educator', 'sports',
    'sport', 'rookie', 'beginner', 'teach', 'learn', 'mastery'],
    relationship: ['friendship', 'dating', 'date', 'partner', 'marriage', 'partnership', 'ties', 'affair', 'assocation', 'state',
    'family', 'brother', 'sister', 'friends', 'friend', 'feelings', 'significant', 'future', 'boundaries', 'sex', 'emotion', 'emotional',
    'breakup', 'loss', 'trust', 'rift', 'break', 'couple', 'history', 'child', 'parent', 'dynamic', 'tied', 'pair', 'drama', 'close', 'adult'],
    beer: ['wine', 'drinks', 'drink', 'beverage', 'wheat', 'brew', 'suds', 'brewery', 'pubs', 'pub', 'pint', 'liver', 'glass', 'bottle',
    'micro', 'drunk', 'piss', 'party', 'drug', 'abuse', 'oktoberfest', 'adult', 'money', 'bar', 'ingest', 'sip', 'bartender', 'consume'],
    knowledge: ['information', 'skills', 'expertise', 'expert', 'learn', 'learning', 'aware', 'awareness', 'process', 'power', 'wisdom',
    'insight', 'mind', 'think', 'understand', 'subject', 'memory', 'possess', 'background', 'perspective', 'data', 'head', 'curiosity', 
    'curious', 'books', 'study', 'school', 'concept', 'concepts', 'intellect', 'smart', 'mastery', 'application', 'apply'],
    improvement: ['better', 'change', 'develop', 'development', 'upgrade', 'renovation', 'renovate', 'progress', 'adjust', 'reform',
    'repair', 'growth', 'grow', 'different', 'difference', 'increase', 'self', 'help', 'fix', 'work', 'practice', 'boost', 'innovation',
    'feedback', 'benefit', 'health', 'time', 'house', 'restoration', 'restore'],
    resolution: ['quality', 'camera', 'photo', 'declaration', 'determined', 'determination', 'decision', 'document', 'proposal', 
    'compromise', 'answer', 'solve', 'purpose', 'graphics', 'performance', 'rate', 'conflict', 'monitor', 'screen', 'closure', 'display', 
    'image', 'color', 'sharp', 'low', 'video', 'poor', 'contrast', 'computer', 'pact', 'debate', 'speech'],
    payment: ['credit', 'debit', 'check', 'cash', 'refund', 'money', 'receipt', 'installment', 'salary', 'fee', 'bonus', 'premium', 'royalty',
    'incentive', 'amount', 'costs', 'cost', 'shipping', 'down', 'bank', 'donation', 'bill', 'charge', 'employer', 'car', 'processing', 
    'receivable', 'sale', 'direct', 'funds', 'tips', 'gratuity', 'overdue', 'tuition', 'missed', 'wallet', 'cards'],
    customer: ['transaction', 'client', 'exchange', 'use', 'retail', 'shop', 'shopper', 'vendor', 'goods', 'food', 'service', 'buyer',
    'hospitality', 'person', 'store', 'order', 'returns', 'associate', 'products'],
    charity: ['foundation', 'money', 'donation', 'donations', 'gift', 'marketing', 'donate', 'organization', 'philanthropy', 'fundraiser', 
    'fundraising', 'handout', 'fund', 'funds', 'taxes', 'tax', 'orphans', 'orphan', 'institution', 'help', 'giveaway', 'donor', 'celebrities',
    'offering', 'benefit', 'aid', 'nonprofit', 'service', 'kindness', 'kind', 'care', 'rescue', 'poor', 'event', 'events', 'children', 'child',
    'contribution', 'contributions'],
    failure: ['success', 'loss', 'lose', 'inability', 'flop', 'lack', 'collapse', 'error', 'malfunction', 'problem', 'problems', 'flunk', 
    'defeat', 'miscalculation', 'system', 'bad', 'learn', 'shame', 'result', 'pain', 'bugs', 'glitch', 'crash', 'avoid', 'threat', 'doubt', 
    'unsuccessful', 'blunder', 'blooper', 'unfortunate', 'disappoint', 'disappointed', 'wrong'],
    initiative: ['project', 'effort', 'program', 'combat', 'petition', 'first', 'plan', 'steps', 'action', 'leadership', 'strategy', 'policy', 
    'pledge', 'momentum', 'create', 'fight', 'energy', 'idea', 'campaign', 'education', 'vision', 'measure', 'begin', 'fund', 'blueprint', 
    'promises', 'promise', 'develop'],
    bonus: ['incentive', 'salary', 'reward', 'premium', 'raise', 'extra', 'commission', 'package', 'winnings', 'win', 'signing', 'package', 
    'prize', 'prizes', 'cost', 'gift', 'benefit', 'wage', 'boost', 'award', 'offer', 'office', 'paid', 'money', 'compensate', 'promotion', 
    'promotional', 'yearly', 'annual', 'earn'],
    permission: ['consent', 'approval', 'license', 'authorize', 'authorization', 'pass', 'clearance', 'clear', 'grant', 'sanction', 'written',
    'allow', 'explicit', 'slip', 'waiver', 'preapproved', 'approve', 'seek', 'obtain'],
    judgment: ['opinion', 'validation', 'decision', 'verdict', 'justice', 'court', 'jury', 'law', 'ruling', 'gossip', 'estimate', 'estimation',
    'mind', 'final', 'sound', 'guilty', 'innocent', 'critique', 'feel', 'fear', 'intuition', 'guilt', 'moral', 'characterization', 'correct', 
    'sentence'],
    requirement: ['necessity', 'ratio', 'necessary', 'prerequisite', 'need', 'essential', 'must', 'obligation', 'mandatory', 'responsibility',
    'demand', 'guideline', 'guidelines', 'minimum', 'limit', 'limitation', 'mandate', 'standard', 'standards', 'rules', 'threshold', 'clause', 
    'qualification', 'qualifications', 'condition', 'measure', 'fulfill', 'criteria', 'stipulation', 'needs', 'job', 'basic'],
    chest: ['heart', 'neck', 'torso', 'back', 'lungs', 'lung', 'breast', 'body', 'box', 'treasure', 'cavity', 'trunk', 'compartment', 
    'loot', 'pirate', 'key', 'skin', 'anatomy', 'wound', 'beat', 'muscle', 'grow', 'pectoral', 'toy', 'tool'],
    personality: ['character', 'identity', 'attitude', 'trait', 'ego', 'individual', 'charisma', 'charm', 'self', 'demeanor', 'humor',
    'temperament', 'qualities', 'emotion', 'emotional', 'extrovert', 'introvert', 'extroverted', 'introverted', 'attribute', 'kind', 
    'mean', 'behavior', 'brain', 'celebrity', 'quirky', 'flirty'],
    coffee: ['drinks', 'drink', 'beverage', 'caffeine', 'espresso', 'bean', 'iced', 'brew', 'cafe', 'consume', 'ingest', 'energy', 'sip', 
    'mug', 'decaf', 'cup', 'roast', 'shop', 'grow', 'breakfast', 'hot', 'cold', 'work', 'office', 'donuts', 'pot', 'table', 'morning', 
    'black'],
    wood: ['table', 'cabin', 'oak', 'lumber', 'maple', 'tree', 'bamboo', 'hard', 'material', 'furniture', 'logs', 'soil', 'twigs', 'cutting',
    'ply', 'trunk', 'pieces', 'sturdy', 'thick', 'house', 'floor', 'paper', 'trees', 'fire', 'camp', 'camping', 'forest', 'cherry', 'chips', 
    'termite', 'stove', 'stoves', 'splinter'],
    garbage: ['recycle', 'recycling', 'trash', 'waste', 'landfill', 'rubbish', 'sewage', 'compost', 'debris', 'junk', 'dump', 'dispose', 
    'disposal', 'bin', 'piles', 'bags', 'bag', 'can', 'cans', 'curbside', 'sanitation', 'smell', 'filth', 'clean', 'crap', 'janitor',
    'truck', 'stink', 'throw', 'toss'],
    response: ['reaction', 'answer', 'reply', 'feedback', 'retort', 'statement', 'comeback', 'counter', 'result', 'rebuttal', 'comment',
    'question', 'post', 'behavior', 'action', 'provoke', 'apology', 'opinion', 'alert', 'excuse', 'interaction', 'email', 'message', 
    'speech', 'clear', 'negative', 'positive', 'reflex'],
    imagination: ['creativity', 'creative', 'mind', 'vision', 'imagery', 'fantasy', 'inspiration', 'child', 'children', 'dream', 
    'curiousity', 'thoughts', 'thought', 'think', 'thinking', 'passion', 'skill', 'brain', 'head', 'idea', 'reality', 'visionary', 
    'instinct', 'story', 'fiction', 'magic', 'conception'],
    marriage: ['wedding', 'divorce', 'family', 'spouse', 'union', 'civil', 'dating', 'partner', 'partnership', 'commitment', 'couple',
    'ceremony', 'engagement', 'proposal', 'arranged', 'contract', 'happy', 'broken', 'kiss', 'ring', 'legal', 'annulment', 'intimate', 
    'intimacy'],
    excitement: ['joy', 'hype', 'anxiety', 'thrill', 'anticipation', 'euphoria', 'passion', 'frenzy', 'happy', 'happiness', 'interest', 
    'feeling', 'feel', 'fun', 'delight', 'drama', 'adrenaline', 'surprise', 'danger', 'pleasure', 'emotion', 'smile', 'reaction'],
    resource: ['support', 'time', 'natural', 'human', 'sustain', 'sustainability', 'funds', 'fund', 'funding', 'oil', 'power', 'energy',
    'commodity', 'minerals', 'asset', 'assests', 'provide', 'valuable', 'vital', 'allocate', 'allocation'],
    pupil: ['iris', 'teacher', 'student', 'eye', 'school', 'students', 'education', 'class', 'mentor', 'learn', 'see', 'vision', 'eyes', 
    'optics', 'optical', 'dilate', 'dilation', 'uniform'],
    weather: ['climate', 'snow', 'wind', 'rain', 'storm', 'sun', 'winter', 'fall', 'atmosphere', 'cold', 'hot', 'air', 'temperature', 
    'bad', 'news', 'forecast', 'proof', 'nature', 'natural', 'spring', 'summer', 'person', 'visibility', 'travel', 'sky'],
    dragon: ['wind', 'fire', 'lizard', 'fly', 'flight', 'wings', 'beast', 'creature', 'legend', 'magic', 'magical', 'knights', 'kings', 
    'dungeon', 'mythical', 'big', 'scales', 'tail', 'egg', 'sky', 'treasure', 'large', 'lord'],
    ocean: ['big', 'sea', 'vast', 'water', 'beach', 'shore', 'salt', 'waves', 'blue', 'creatures', 'whale', 'fish', 'mermaid', 'currents', 
    'boat', 'ship', 'travel', 'floor', 'eyes', 'world', 'large', 'fear', 'shark', 'moon'],
    war: ['wounds', 'wound', 'military', 'fight', 'combat', 'battle', 'conflict', 'struggle', 'peace', 'invasion', 'weapon', 'death', 'crisis', 
    'campaign', 'civil', 'world', 'strategy', 'zone', 'nuclear', 'cold', 'machine', 'violence', 'win', 'lose', 'declare', 'anti', 'army', 
    'soldier', 'lord', 'aftermath', 'destruction', 'prisoner']
}]



console.log(wordPool)

/*---------------------------- Variables (state) ----------------------------*/
let winningWords =[]
let assassinWords = []
let bystanderWords = []



/*------------------------ Cached Element References ------------------------*/



/*-------------------------------- Functions --------------------------------*/



/*----------------------------- Event Listeners -----------------------------*/



